version: "3"
services:
  simple-instagram-bot:
    build: .
    restart: always
    volumes:
      - ./app:/app
    logging:
      driver: "json-file"
      options:
          max-size: "2m"
          max-file: "10"
    environment:
      - API_TOKEN=5480367721:AAEsbl6lt436BXD36AQiR9_RJMF9lW9si9I
